### ISSUE TITLE
Would the transporter network baseline get released?

### ISSUE THREAD

**Issue by mlzxy** [haosulab/ManiSkill#143]
Hi, 

It was mentioned in the paper that transporter network is tested on the AssemblingKits task (table 5). I wonder whether the corresponding implementation will be released. 

Thanks!

**Comment by StoneT2000** [comment]
We were able to release the TPN baseline here https://github.com/haosulab/ManiSkill2-SPA

The results don't match the paper completely due to changes in the benchmark and envs but it should still work. Note that this baseline is a very "minimal" baseline, there is a lot of room for tuning especially given that ManiSkill2 assembling kit environment is more realistic and strict than what TPN tests on.

**Comment by mlzxy** [comment]
Got it. Thanks for your help!
