### ISSUE TITLE
General Question about Physics Engine

### ISSUE THREAD

**Issue by mlzxy** [haosulab/ManiSkill#148]
Hi, 

I wonder what physics engine is used to support ManiSkill2. This could be important for getting a sense of how well contacts / frictions are simulated. 

I understand ManiSkill2 uses SAPIEN. Does SAPIEN use other well-tested physics engines such as Mujoco / Bullet? 

Thanks!

**Comment by fbxiang** [comment]
The rigid body part the current ManiSkill2 (SAPIEN) is using PhysX 4.

The soft body simulation is a MPM simulator we implemented from scratch. And the contact models contain many tricks that do not strictly follow mechanical principles, in order to make it visually plausible with real-time performance.

**Comment by mlzxy** [comment]
That's reassuring. Thank you!
