### ISSUE TITLE
State Observation Ranges in Vision-Based Training

### ISSUE THREAD

**Issue by SumeetBatra** [haosulab/ManiSkill#258]
Hi Folks,

I am using the rgbd obs_mode to train a visuomotor policy with RL that also incorporates the low dimensional state information into the policy. I'm wondering if you have more informative ranges on each dimension of the state tensor than (-inf, inf)? I'm not using PPO, although it may be possible to use the same running statistics-based obs normalizer in my method as they do. However, I would like to avoid any potential non-stationarity in the state tensor by simply normalizing the tensor with their fixed maximum values if possible. Thanks!

**Comment by StoneT2000** [comment]
this depends on a task by task basis unfortunately. Robot proprioception data can be more easily normalized since there are joint limits. 

Other state data might not be easy to normalize automatically if it is task specific.

**Comment by StoneT2000** [comment]
In terms of robot learning it works sufficiently fine to just use the state data as is. Propioceptive data tends to always be no larger than pi

Tasks where state data could potentially go beyond a fixed value (like mobile manipulation which we will add extensive support for in the future) will be built to use more relative data instead of absolute values

**Comment by StoneT2000** [comment]
Closing this issue as it has gone stale. Feel free to reopen if not.
