### ISSUE TITLE
Error with motion planning: ManiSkill must have unique names

### ISSUE THREAD

**Issue by dennisushi** [haosulab/ManiSkill#414]
```python -m mani_skill.examples.motionplanning.panda.run -e "StackCube-v1" --vis # opens up the GUI```
produces 1/10 successful demonstration and then causes
```AssertionError: built actors in ManiSkill must have unique names and cannot be None or empty strings```
This can be avoided by commenting out the line
https://github.com/haosulab/ManiSkill/blob/8ce2c8126fa5553af94de026b73ac1c791025fa8/mani_skill/utils/building/actor_builder.py#L179
but this isn't a viable long-term fix. 

PS. some of the listed environments https://maniskill.readthedocs.io/en/latest/user_guide/concepts/environments.html are no longer accessible. e.g. ```gymnasium.error.NameNotFound: Environment `Pinch` doesn't exist.```

**Comment by StoneT2000** [comment]
Oh that documentation link is old. I have removed that page just now, webpage is rebuilding. All environments are listed here: https://maniskill.readthedocs.io/en/latest/tasks/index.html

For the bug I will investigate. It is just a bug with turning the visualization mode since it keeps rebuilding an object.
