### ISSUE TITLE
Computing end effector pose of robot

### ISSUE THREAD

**Issue by hq-sg** [haosulab/ManiSkill#483]
Thank you for the excellent code. While using the arm in the simulator, I find it a bit confusing to calculate the robot arm's end effector pose from the robot's joint positions (qpos). Could you please explain how to do this efficiently?

<img width="1146" alt="Screenshot 2024-08-08 at 09 43 29" src="https://github.com/user-attachments/assets/e8189e3d-a712-4850-8129-ad9439913caf">

Regarding the Fetch robot described in the repository, the observation data appears as shown in the attached image. How can I calculate the end effector pose using this information?

Thank you very much.

**Comment by StoneT2000** [comment]
Either use a forward kinematic library or directly access link poses. The end-effector could be the robot link. By default without adding it yourself, maniskill does not output EE poses since we don't know which link is the link you might want. If you are building a custom task you have to add it in the `_get_obs_extra` function. 

For fetch specifically, the gripper/end-effector link is called "gripper_link" (you can check by using the GUI or inspecting the URDF). To get the pose in world coordinates, run `self.agent.robot.links_map["gripper_link"].pose`. the self.agent.robot is the articulation object of the robot and has a lot of properties you can access,

**Comment by hq-sg** [comment]
Thanks for your quick reply~
