### ISSUE TITLE
Question on the effects of `use_target` in a controller config object

### ISSUE THREAD

**Issue by hesic73** [haosulab/ManiSkill#498]
Hello! I've read the [documentation on Controllers](https://maniskill.readthedocs.io/en/latest/user_guide/concepts/controllers.html) and the [source code](https://github.com/haosulab/ManiSkill/blob/main/mani_skill/agents/controllers/pd_joint_pos.py). However, I still have some questions about the `use_target` property of a controller config object.

My current understanding is as follows:

- If `use_delta=False`, `use_target` does not alter the behavior of the controller.
- If `use_delta=True` and `use_target=False`, the controller behaves like a common delta controller, where the target qpos is set to current qpos + delta.

However, I am a bit confused about the behavior when `use_delta=True` and `use_target=True`. IInstead of using the current qpos, the controller uses `self._target_qpos`.  Although `PDJointPosController` has a `_target_qpos` attribute, it seems that this attribute is always initialized to the qpos on reset, which makes it unclear to me what purpose `use_target=True` serves in this context. Could you please explain how `use_target=True` is intended to be used? Thank you very much!

By the way, I noticed that `PDJointPosControllerConfig.use_delta` defaults to `False`, while `PDEEPosControllerConfig.use_delta` defaults to `True`. Is this difference in default values intentional?

**Comment by StoneT2000** [comment]
The defaults are just defaults, we usually expect user to set those values (in the future i'll require it to be set since it vastly changes behavior)

I think the code here can make some sense:
https://github.com/haosulab/ManiSkill/blob/main/mani_skill/agents/controllers/pd_joint_pos.py#L73C5-L91C43

if use delta is true,
- if use target is true, then essentially actions will be added to the current qpos target by a delta value, the simulator will keep trying to get the robot to approach that qpos target
- if use target is false, then actions will be added to the current robot qpos.

Key difference is what the robot is trying to reach. Either its qpos+action, or qpos_target+action. The target can be influenced by past actions so if in previous timestep the target was too far away and robot didn't reach it, taking a 0 action will cause the robot to move still since the robot isn't at the target when use target is true

**Comment by hesic73** [comment]
Thank you for the clarification!  So when `use_delta=True` and `use_target=True`, the action is the delta of the target position.
Given this, if I were to implement something like DexPoint, where the end effector controller is used to control the arm to grasp an object, which mode  is recommended?

**Comment by StoneT2000** [comment]
just use the default pd_ee_delta_pose, which is use_delta=True and use_Target=False. This is pretty common.
