### ISSUE TITLE
Coordinate Transformation for pd_ee_delta_pose in PushCube-v1 Dataset

### ISSUE THREAD

**Issue by zqy-an** [haosulab/ManiSkill#642]
Hello,
We are using the dataset available on Hugging Face, specifically examining the first trajectory of PushCube-v1.  We have noticed that when using `pd_ee_delta_pose`, the `action` does not equate to `delta_tcp_pose`.

We found some explanations at [this link](https://maniskill.readthedocs.io/en/latest/user_guide/concepts/controllers.html), but we are still unclear about how to specifically transform the coordinates.

Could you please provide more detailed guidance on how to perform this transformation?

![fig1](https://github.com/user-attachments/assets/1f037bf8-1f08-4b8a-8b1b-b288d9e2105d)

**Comment by StoneT2000** [comment]
Could you share a script to reproduce this?

I will also note that we run by default 5 physics steps for every 1 control step with a sim freq of 100. It is possible that the robot has not reached the target (current_ee_pose + delta_pose) in the one control step. Although a difference of 0.2 in the X direction seems concerning. Difference in Z could be due to hitting the table and so you are prevented from going under it (hence larger z difference values).

**Comment by StoneT2000** [comment]
Hi @zqy-an is this still an issue?

**Comment by zqy-an** [comment]
Thanks!

However, I am still very interested in how the action is converted into delta_pose. Could you please tell me where I can view the code responsible for this process?

**Comment by StoneT2000** [comment]
See the replay trajectory tool under mani_skill/trajectory/replay_trajectory.py for how we convert action spaces.
