### ISSUE TITLE
ManiSkill3-Learn 

### ISSUE THREAD

**Issue by robot-feng** [haosulab/ManiSkill#744]
"Hello, may I ask if there are any plans from the official team to update the ManiSkill-Learn library to be compatible with ManiSkill3? If such plans are not available at the moment, how should I modify and adapt the library to work in the ManiSkill3 environment?"

**Comment by StoneT2000** [comment]
I generally would recommend just using the baselines we have now in the examples/baselines folder, which provide PPO, SAC, TDMPC2, and several common imitation learning algorithms baselines. They are written to be independent of each other for easier readability so it is in a different style to ManiSkill-Learn which is more modularized.

Otherwise maybe @xuanlinli17 may have an answer, he maintained that library previously.

**Comment by xuanlinli17** [comment]
Unfortunately I don't have time to write ManiSkill3-Learn. You can use the existing algorithms from the ManiSkill repo or adopt from ManiSkill2-Learn.

**Comment by robot-feng** [comment]
@StoneT2000 Thanks,I will try.
